(()=>{
const $=s=>document.querySelector(s);let lang=localStorage.ilLang||"Japonês",voice=localStorage.ilVoice!=="off",h=JSON.parse(localStorage.ilHistory||"[]"),stream=null,currentAudio=null,callMode=null,recognition=null,listening=false;
const lc={Japonês:"ja-JP",Inglês:"en-US",Espanhol:"es-ES",Francês:"fr-FR",Coreano:"ko-KR",Português:"pt-BR",Outro:"pt-BR"};
$("#voice").textContent=voice?"🔊 Voz ligada":"🔇 Voz desligada";
$("#enter").onclick=()=>{$("#login").classList.add("hide");$("#app").classList.remove("hide")};
function stopListening(){listening=false;if(recognition){try{recognition.stop()}catch(e){}}}
function stopMedia(){stopListening();callMode=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=$("#userVideo");if(v){v.srcObject=null;v.hidden=true}$("#userPlaceholder")?.removeAttribute("hidden");if($("#cameraStatus"))$("#cameraStatus").textContent="Câmera opcional";$("#videoRoom")?.classList.remove("in-call");$("#miokoVideo")?.classList.remove("calling","speaking")}
$("#exitCourse").onclick=()=>{speechSynthesis?.cancel();if(currentAudio){currentAudio.pause();currentAudio=null}stopMedia();$("#app").classList.add("hide");$("#login").classList.remove("hide");$("#pass").value="";scrollTo(0,0)};
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-mode]").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
document.querySelectorAll("[data-lang]").forEach(b=>{if(b.dataset.lang===lang)b.classList.add("sel");b.onclick=()=>{document.querySelectorAll("[data-lang]").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");lang=b.dataset.lang;localStorage.ilLang=lang;$("#status").textContent=lang+" • avaliação adaptativa"}});
function add(c,t,save=false){const d=document.createElement("div");d.className="msg "+c;d.innerHTML="<b>"+(c==="user"?"Você":"Mioko IA")+"</b><p></p>";d.querySelector("p").textContent=t;$("#chat").appendChild(d);$("#chat").scrollTop=$("#chat").scrollHeight;if(save){h.push({role:c==="ai"?"assistant":"user",content:t});h=h.slice(-30);localStorage.ilHistory=JSON.stringify(h)}}
function cleanSpeech(t){return String(t).replace(/[*#_`~]+/g," ").replace(/https?:\/\/\S+/g," ").replace(/\s+/g," ").trim()}
function headers(){const c=window.IL_TALK_CONFIG||{},x={"Content-Type":"application/json"};if(c.SUPABASE_PUBLISHABLE_KEY){x.apikey=c.SUPABASE_PUBLISHABLE_KEY;return x}if(c.SUPABASE_ANON_KEY){x.apikey=c.SUPABASE_ANON_KEY;x.Authorization="Bearer "+c.SUPABASE_ANON_KEY}return x}
async function say(t){if(!voice)return;const text=cleanSpeech(t),c=window.IL_TALK_CONFIG||{};speechSynthesis?.cancel();if(currentAudio){currentAudio.pause();currentAudio=null}const face=$("#miokoVideo");try{if(!c.VOICE_ENDPOINT)throw Error("sem il-voice");const r=await fetch(c.VOICE_ENDPOINT,{method:"POST",headers:headers(),body:JSON.stringify({text,language:lang})});if(!r.ok)throw Error("il-voice HTTP "+r.status);const blob=await r.blob(),url=URL.createObjectURL(blob),a=new Audio(url);currentAudio=a;a.onplay=()=>face?.classList.add("speaking");a.onended=()=>{face?.classList.remove("speaking");URL.revokeObjectURL(url);currentAudio=null;if(callMode) setTimeout(startListening,250)};a.onerror=()=>{face?.classList.remove("speaking");URL.revokeObjectURL(url)};await a.play();return}catch(e){console.warn("il-voice indisponível; usando voz local",e)}
if("speechSynthesis"in window){const u=new SpeechSynthesisUtterance(text);u.lang=lc[lang]||"pt-BR";const vs=speechSynthesis.getVoices();const prefix=u.lang.split("-")[0];u.voice=vs.find(v=>v.lang===u.lang&&/female|femin|maria|luciana|francisca|google/i.test(v.name))||vs.find(v=>v.lang.startsWith(prefix))||null;u.onstart=()=>face?.classList.add("speaking");u.onend=()=>{face?.classList.remove("speaking");if(callMode)setTimeout(startListening,250)};u.onerror=()=>face?.classList.remove("speaking");speechSynthesis.speak(u)}}
$("#voice").onclick=()=>{voice=!voice;localStorage.ilVoice=voice?"on":"off";$("#voice").textContent=voice?"🔊 Voz ligada":"🔇 Voz desligada";if(!voice){speechSynthesis?.cancel();if(currentAudio){currentAudio.pause();currentAudio=null}$("#miokoVideo")?.classList.remove("speaking")}};
$("#begin").onclick=()=>{const t=`Olá. Sou Mioko, Professora Virtual de Idiomas. Podemos conversar sobre qualquer assunto e eu adapto o ensino de ${lang} ao seu nível. O que você gostaria de conversar ou aprender?`;add("ai",t,true);say(t)};
function endpoint(){const c=window.IL_TALK_CONFIG||{};return c.AI_ENDPOINT||(c.SUPABASE_PROJECT_REF?`https://${c.SUPABASE_PROJECT_REF}.supabase.co/functions/v1/il-ai`:"")}
async function send(x){const m=(x||$("#text").value).trim();if(!m)return;add("user",m,true);$("#text").value="";const ep=endpoint();if(!ep){add("ai","⚙️ Falta ligar a função il-ai em config.js.");return}const wait=document.createElement("div");wait.className="msg ai";wait.innerHTML="<b>Mioko IA</b><p>🧠 Pensando...</p>";$("#chat").appendChild(wait);try{const r=await fetch(ep,{method:"POST",headers:headers(),body:JSON.stringify({message:m,language:lang,history:h.slice(0,-1).slice(-16)})});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw Error("Backend devolveu resposta inválida")};if(!r.ok)throw Error("HTTP "+r.status+": "+(d.error||d.message||"Falha"));const a=d.answer||d.reply||d.output_text||d.target||d.japanese;if(!a)throw Error("A função respondeu sem texto.");wait.remove();add("ai",String(a),true);say(String(a))}catch(e){wait.remove();add("ai","❌ IA não conectou: "+e.message)}}
$("#send").onclick=()=>send();$("#text").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>send(b.dataset.q));
async function startVideo(){if(stream){stopMedia();$("#videoCall").textContent="📹 Vídeo IA";$("#voiceCall").textContent="📞 Chamada IA";return}try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});callMode="video";const v=$("#userVideo");v.srcObject=stream;v.hidden=false;$("#userPlaceholder").hidden=true;$("#cameraStatus").textContent="Câmera e microfone ativos";$("#videoRoom").classList.add("in-call");$("#miokoVideo").classList.add("calling");$("#videoCall").textContent="⏹ Encerrar vídeo";add("ai","Videoconferência com a Mioko Sensei iniciada. Pode falar comigo ou continuar escrevendo normalmente.");startListening();}catch(e){add("ai","Não consegui abrir câmera/microfone: "+e.message+". Você pode continuar escrevendo normalmente.")}}
$("#videoCall").onclick=startVideo;
$("#voiceCall").onclick=()=>{if(callMode==="voice"){stopListening();callMode=null;$("#miokoVideo").classList.remove("calling","speaking");$("#voiceCall").textContent="📞 Chamada IA";add("ai","Chamada encerrada.");return}voice=true;callMode="voice";localStorage.ilVoice="on";$("#voice").textContent="🔊 Voz ligada";$("#miokoVideo").classList.add("calling");add("ai","Chamada com a Mioko Sensei iniciada. Pode falar comigo ou escrever; eu responderei por áudio.");$("#voiceCall").textContent="⏹ Encerrar chamada";startListening()};
$("#photo").onclick=()=>$("#photoIn").click();$("#file").onclick=()=>$("#fileIn").click();["#photoIn","#fileIn"].forEach(id=>$(id).onchange=e=>{const f=e.target.files[0];if(f)add("user","Arquivo selecionado: "+f.name+" (upload seguro será ligado ao backend).")});
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;function startListening(){if(!callMode||!SR||listening||currentAudio)return;recognition=new SR();recognition.lang=lc[lang]||"pt-BR";recognition.continuous=false;recognition.interimResults=false;recognition.onstart=()=>{listening=true;$("#mic").textContent="🎙️ Ouvindo..."};recognition.onresult=e=>{const spoken=e.results[e.results.length-1][0].transcript.trim();if(spoken){$("#text").value=spoken;send(spoken)}};recognition.onend=()=>{listening=false;$("#mic").textContent="🎙️ Microfone opcional";if(callMode&&!currentAudio)setTimeout(startListening,500)};recognition.onerror=e=>{listening=false;$("#mic").textContent="🎙️ Microfone opcional";if(!["no-speech","aborted"].includes(e.error))add("ai","Microfone: "+e.error+". Você pode continuar digitando.")};try{recognition.start()}catch(e){listening=false}}if(SR){$("#mic").onclick=()=>{if(callMode){if(listening)stopListening();else startListening()}else{callMode="voice";$("#miokoVideo").classList.add("calling");startListening()}}}else $("#mic").onclick=()=>alert("Este navegador não oferece reconhecimento de voz. Continue a conversa escrevendo; a Mioko continuará respondendo por áudio.");
})();
